### ISSUE TITLE
Failed to emerge dev-python/Kivy

### ISSUE THREAD

**Issue by fpemud** [g1itch/altcoins-overlay#1]
Some questions:
1. it seems there's git fetch operations in compile stage?
2. it seems the ebuild is calling pip to download something (cython?) when it fails?

```
localhost / # emerge -1 Kivy
Calculating dependencies... done!
>>> Verifying ebuild manifests
>>> Emerging (1 of 1) dev-python/Kivy-1.11.1-r1::altcoins
>>> Failed to emerge dev-python/Kivy-1.11.1-r1, Log file:
>>>  '/var/tmp/portage/dev-python/Kivy-1.11.1-r1/temp/build.log'
>>> Jobs: 0 of 1 complete, 1 failed                 Load avg: 0.27, 0.13, 0.04
 * Package:    dev-python/Kivy-1.11.1-r1
 * Repository: altcoins
 * USE:        abi_x86_64 amd64 cairo elibc_glibc gstreamer kernel_linux python_targets_python3_6 python_targets_python3_7 python_targets_python3_8 sdl userland_GNU
 * FEATURES:   network-sandbox preserve-libs sandbox userpriv usersandbox
>>> Unpacking source...
>>> Unpacking Kivy-1.11.1.tar.gz to /var/tmp/portage/dev-python/Kivy-1.11.1-r1/work
>>> Source unpacked in /var/tmp/portage/dev-python/Kivy-1.11.1-r1/work
>>> Preparing source in /var/tmp/portage/dev-python/Kivy-1.11.1-r1/work/kivy-1.11.1 ...
 * Applying 1.11-setup.patch ...
 [ ok ]
 * Will copy sources from /var/tmp/portage/dev-python/Kivy-1.11.1-r1/work/kivy-1.11.1
 * python3_6: copying to /var/tmp/portage/dev-python/Kivy-1.11.1-r1/work/kivy-1.11.1-python3_6
 * python3_7: copying to /var/tmp/portage/dev-python/Kivy-1.11.1-r1/work/kivy-1.11.1-python3_7
 * python3_8: copying to /var/tmp/portage/dev-python/Kivy-1.11.1-r1/work/kivy-1.11.1-python3_8
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/dev-python/Kivy-1.11.1-r1/work/kivy-1.11.1 ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/dev-python/Kivy-1.11.1-r1/work/kivy-1.11.1 ...
 * python3_6: running distutils-r1_run_phase python_compile
python3.6 setup.py build_ext --inplace
fatal: not a git repository (or any of the parent directories): .git
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f9d5e902358>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/cython/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f9d5e9024e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/cython/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f9d5e902160>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/cython/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f9d5e902390>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/cython/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f9d5e902518>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/cython/
ERROR: Could not find a version that satisfies the requirement cython!=0.27,!=0.27.2,<=0.29.15,>=0.24 (from versions: none)
ERROR: No matching distribution found for cython!=0.27,!=0.27.2,<=0.29.15,>=0.24
Using setuptools
Environ change use_sdl2 -> True
Environ change use_gstreamer -> True
Using this graphics system: OpenGL
GStreamer found via pkg-config
SDL2 found via pkg-config
SDL2: found SDL header at /usr/include/SDL2/SDL.h
SDL2: found SDL_mixer header at /usr/include/SDL2/SDL_mixer.h
SDL2: found SDL_ttf header at /usr/include/SDL2/SDL_ttf.h
SDL2: found SDL_image header at /usr/include/SDL2/SDL_image.h
Pango: pangoft2 found via pkg-config
{'libraries': ['pangoft2-1.0', 'pango-1.0', 'gobject-2.0', 'glib-2.0', 'fontconfig', 'freetype'], 'include_dirs': ['kivy/include', '/usr/include/pango-1.0', '/usr/include/glib-2.0', '/usr/lib64/glib-2.0/include', '/usr/lib64/libffi/include', '/usr/include/fribidi', '/usr/include/freetype2', '/usr/include/uuid', '/usr/include/harfbuzz'], 'library_dirs': [], 'extra_link_args': [], 'extra_compile_args': [], 'depends': ['lib/pango/pangoft2.pxi', 'lib/pango/pangoft2.h']}
ERROR: Dependency for context.pyx not resolved: config.pxi
ERROR: Dependency for compiler.pyx not resolved: config.pxi
ERROR: Dependency for context_instructions.pyx not resolved: config.pxi
ERROR: Dependency for fbo.pyx not resolved: config.pxi
ERROR: Dependency for gl_instructions.pyx not resolved: config.pxi
ERROR: Dependency for instructions.pyx not resolved: config.pxi
ERROR: Dependency for opengl.pyx not resolved: config.pxi
ERROR: Dependency for opengl_utils.pyx not resolved: config.pxi
ERROR: Dependency for shader.pyx not resolved: config.pxi
ERROR: Dependency for stencil_instructions.pyx not resolved: config.pxi
ERROR: Dependency for scissor_instructions.pyx not resolved: config.pxi
ERROR: Dependency for texture.pyx not resolved: config.pxi
ERROR: Dependency for vbo.pyx not resolved: config.pxi
ERROR: Dependency for vertex.pyx not resolved: config.pxi
ERROR: Dependency for vertex_instructions.pyx not resolved: config.pxi
ERROR: Dependency for cgl.pyx not resolved: config.pxi
ERROR: Dependency for cgl_mock.pyx not resolved: config.pxi
ERROR: Dependency for cgl_gl.pyx not resolved: config.pxi
ERROR: Dependency for cgl_glew.pyx not resolved: config.pxi
ERROR: Dependency for cgl_sdl2.pyx not resolved: config.pxi
ERROR: Dependency for svg.pyx not resolved: config.pxi
 Traceback (most recent call last):
   File "/usr/lib64/python3.6/site-packages/setuptools/installer.py", line 126, in fetch_build_egg
     subprocess.check_call(cmd)
   File "/usr/lib64/python3.6/subprocess.py", line 311, in check_call
     raise CalledProcessError(retcode, cmd)
 subprocess.CalledProcessError: Command '['/usr/bin/python3.6', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/tmp/portage/dev-python/Kivy-1.11.1-r1/temp/tmpa1mekcwk', '--quiet', 'cython!=0.27,!=0.27.2,<=0.29.15,>=0.24']' returned non-zero exit status 1.
 
 The above exception was the direct cause of the following exception:
 
 Traceback (most recent call last):
   File "setup.py", line 1204, in <module>
     'tuio': ['oscpy']
   File "/usr/lib64/python3.6/site-packages/setuptools/__init__.py", line 152, in setup
     _install_setup_requires(attrs)
   File "/usr/lib64/python3.6/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
     dist.fetch_build_eggs(dist.setup_requires)
   File "/usr/lib64/python3.6/site-packages/setuptools/dist.py", line 676, in fetch_build_eggs
     replace_conflicting=True,
   File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 766, in resolve
     replace_conflicting=replace_conflicting
   File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 1049, in best_match
     return self.obtain(req, installer)
   File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 1061, in obtain
     return installer(requirement)
   File "/usr/lib64/python3.6/site-packages/setuptools/dist.py", line 732, in fetch_build_egg
     return fetch_build_egg(self, req)
   File "/usr/lib64/python3.6/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
     raise DistutilsError(str(e)) from e
 distutils.errors.DistutilsError: Command '['/usr/bin/python3.6', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/tmp/portage/dev-python/Kivy-1.11.1-r1/temp/tmpa1mekcwk', '--quiet', 'cython!=0.27,!=0.27.2,<=0.29.15,>=0.24']' returned non-zero exit status 1.
 * ERROR: dev-python/Kivy-1.11.1-r1::altcoins failed (compile phase):
 *   (no error message)
 * 
 * Call stack:
 *     ebuild.sh, line  125:  Called src_compile
 *   environment, line 3929:  Called distutils-r1_src_compile
 *   environment, line 1246:  Called _distutils-r1_run_foreach_impl 'python_compile'
 *   environment, line  414:  Called python_foreach_impl 'distutils-r1_run_phase' 'python_compile'
 *   environment, line 3538:  Called multibuild_foreach_variant '_python_multibuild_wrapper' 'distutils-r1_run_phase' 'python_compile'
 *   environment, line 2840:  Called _multibuild_run '_python_multibuild_wrapper' 'distutils-r1_run_phase' 'python_compile'
 *   environment, line 2838:  Called _python_multibuild_wrapper 'distutils-r1_run_phase' 'python_compile'
 *   environment, line  859:  Called distutils-r1_run_phase 'python_compile'
 *   environment, line 1239:  Called python_compile
 *   environment, line 3278:  Called esetup.py 'build_ext' '--inplace'
 *   environment, line 1906:  Called die
 * The specific snippet of code:
 *       "${@}" || die "${die_args[@]}";
 * 
 * If you need support, post the output of `emerge --info '=dev-python/Kivy-1.11.1-r1::altcoins'`,
 * the complete build log and the output of `emerge -pqv '=dev-python/Kivy-1.11.1-r1::altcoins'`.
 * The complete build log is located at '/var/tmp/portage/dev-python/Kivy-1.11.1-r1/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dev-python/Kivy-1.11.1-r1/temp/environment'.
 * Working directory: '/var/tmp/portage/dev-python/Kivy-1.11.1-r1/work/kivy-1.11.1-python3_6'
 * S: '/var/tmp/portage/dev-python/Kivy-1.11.1-r1/work/kivy-1.11.1'

 * Messages for package dev-python/Kivy-1.11.1-r1:

 * ERROR: dev-python/Kivy-1.11.1-r1::altcoins failed (compile phase):
 *   (no error message)
 * 
 * Call stack:
 *     ebuild.sh, line  125:  Called src_compile
 *   environment, line 3929:  Called distutils-r1_src_compile
 *   environment, line 1246:  Called _distutils-r1_run_foreach_impl 'python_compile'
 *   environment, line  414:  Called python_foreach_impl 'distutils-r1_run_phase' 'python_compile'
 *   environment, line 3538:  Called multibuild_foreach_variant '_python_multibuild_wrapper' 'distutils-r1_run_phase' 'python_compile'
 *   environment, line 2840:  Called _multibuild_run '_python_multibuild_wrapper' 'distutils-r1_run_phase' 'python_compile'
 *   environment, line 2838:  Called _python_multibuild_wrapper 'distutils-r1_run_phase' 'python_compile'
 *   environment, line  859:  Called distutils-r1_run_phase 'python_compile'
 *   environment, line 1239:  Called python_compile
 *   environment, line 3278:  Called esetup.py 'build_ext' '--inplace'
 *   environment, line 1906:  Called die
 * The specific snippet of code:
 *       "${@}" || die "${die_args[@]}";
 * 
 * If you need support, post the output of `emerge --info '=dev-python/Kivy-1.11.1-r1::altcoins'`,
 * the complete build log and the output of `emerge -pqv '=dev-python/Kivy-1.11.1-r1::altcoins'`.
 * The complete build log is located at '/var/tmp/portage/dev-python/Kivy-1.11.1-r1/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dev-python/Kivy-1.11.1-r1/temp/environment'.
 * Working directory: '/var/tmp/portage/dev-python/Kivy-1.11.1-r1/work/kivy-1.11.1-python3_6'
 * S: '/var/tmp/portage/dev-python/Kivy-1.11.1-r1/work/kivy-1.11.1'
```

**Comment by g1itch** [comment]
It is because of the recent upstream changes to python eclasses. Now I have to rewrite all the ebuilds related to python. Sad.

**Comment by fpemud** [comment]
Now I can build dev-python/Kivy after I downgrade dev-python/cython from version "0.29.21" to version "0.29.15".
The build failure is due to the "MAX_CYTHON_STRING = '0.29.15'" line in "files/1.11-setup.patch".
The git-fetch and download operation is because python distutils tries to install cython from internet if no cython version it requires is installed.
Maybe you can change MAX_CYTHON_STRING to a bigger value, such as "0.29.99".
Thanks for this ebuild.
